CREATE TABLE IF NOT EXISTS "users" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "patients" (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(20),
    dni VARCHAR(20) UNIQUE,
    CONSTRAINT fk_patient_user FOREIGN KEY (id) REFERENCES "users"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "psychologists" (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    specialty VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(20),
    dni VARCHAR(20) UNIQUE,
    CONSTRAINT fk_psychologist_user FOREIGN KEY (id) REFERENCES "users"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "rooms" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "appointments" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    patient_id BIGINT NOT NULL,
    psychologist_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES "patients"(id),
    CONSTRAINT fk_appointment_psychologist FOREIGN KEY (psychologist_id) REFERENCES "psychologists"(id),
    CONSTRAINT fk_appointment_room FOREIGN KEY (room_id) REFERENCES "rooms"(id),
    CONSTRAINT chk_time_order CHECK (end_time > start_time)
);

CREATE INDEX IF NOT EXISTS idx_appointments_psychologist_time 
    ON "appointments" (psychologist_id, start_time, end_time);
    
CREATE INDEX IF NOT EXISTS idx_appointments_patient_time 
    ON "appointments" (patient_id, start_time, end_time);
    
CREATE INDEX IF NOT EXISTS idx_appointments_room_time 
    ON "appointments" (room_id, start_time, end_time);
