CREATE TABLE IF NOT EXISTS "users" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "patients" (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(20),
    dni VARCHAR(20) UNIQUE,
    CONSTRAINT fk_patient_user FOREIGN KEY (id) REFERENCES "users"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "psychologists" (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    specialty VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(20),
    dni VARCHAR(20) UNIQUE,
    CONSTRAINT fk_psychologist_user FOREIGN KEY (id) REFERENCES "users"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "rooms" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "appointments" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    patient_id BIGINT NOT NULL,
    psychologist_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES "patients"(id),
    CONSTRAINT fk_appointment_psychologist FOREIGN KEY (psychologist_id) REFERENCES "psychologists"(id),
    CONSTRAINT fk_appointment_room FOREIGN KEY (room_id) REFERENCES "rooms"(id),
    CONSTRAINT chk_time_order CHECK (end_time > start_time)
);

CREATE INDEX IF NOT EXISTS idx_appointments_psychologist_time 
    ON "appointments" (psychologist_id, start_time, end_time);
    
CREATE INDEX IF NOT EXISTS idx_appointments_patient_time 
    ON "appointments" (patient_id, start_time, end_time);
    
CREATE INDEX IF NOT EXISTS idx_appointments_room_time 
    ON "appointments" (room_id, start_time, end_time);

-- === Índices para Búsqueda Difusa (Fuzzy Search) con pg_trgm ===

-- Índice para pacientes (Usamos LOWER para que sea insensible a mayúsculas/minúsculas)
CREATE INDEX IF NOT EXISTS trgm_idx_patients_name 
    ON "patients" 
    USING GIN (LOWER(name) gin_trgm_ops);

-- Índice para psicólogos
CREATE INDEX IF NOT EXISTS trgm_idx_psychologists_name 
    ON "psychologists" 
    USING GIN (LOWER(name) gin_trgm_ops);

-- === Tabla para Refresh Token Sessions ===
-- Permite gestionar tokens con estado para máxima seguridad:
-- - Invalidar tokens usados (one-time use)
-- - Detectar reutilización de tokens (posible robo)
-- - Cerrar sesión en todos los dispositivos

CREATE TABLE IF NOT EXISTS "refresh_token_sessions" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_id VARCHAR(255) UNIQUE NOT NULL,  -- UUID (jti claim del JWT)
    device_info VARCHAR(512),                -- User-Agent o identificador del dispositivo
    ip_address VARCHAR(45),                  -- IPv4 o IPv6
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    replaced_by_token_id VARCHAR(255),       -- Para detectar reutilización (token chain)
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES "users"(id) ON DELETE CASCADE
);

-- Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_refresh_token_user_id 
    ON "refresh_token_sessions" (user_id);

CREATE INDEX IF NOT EXISTS idx_refresh_token_token_id 
    ON "refresh_token_sessions" (token_id);

CREATE INDEX IF NOT EXISTS idx_refresh_token_active 
    ON "refresh_token_sessions" (user_id, revoked, expires_at) 
    WHERE revoked = false;

-- Índice para limpieza de tokens expirados
CREATE INDEX IF NOT EXISTS idx_refresh_token_expires 
    ON "refresh_token_sessions" (expires_at);
