-- ============================================
-- V1__initial_schema.sql
-- Mental Health Clinic - Initial Schema
-- ============================================
-- This migration creates the initial database schema
-- for the Mental Health Clinic application.
-- ============================================

-- === Extensions ===
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "btree_gist";

-- === Users Table ===
CREATE TABLE IF NOT EXISTS "users" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_username ON "users" (username);
CREATE INDEX IF NOT EXISTS idx_users_role ON "users" (role);

-- === Patients Table ===
CREATE TABLE IF NOT EXISTS "patients" (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(20),
    dni VARCHAR(20) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_patient_user FOREIGN KEY (id) REFERENCES "users"(id) ON DELETE CASCADE
);

-- Fuzzy search index for patient names
CREATE INDEX IF NOT EXISTS trgm_idx_patients_name
    ON "patients"
    USING GIN (LOWER(name) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_patients_dni ON "patients" (dni);
CREATE INDEX IF NOT EXISTS idx_patients_email ON "patients" (email);

-- === Psychologists Table ===
CREATE TABLE IF NOT EXISTS "psychologists" (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    specialty VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(20),
    dni VARCHAR(20) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_psychologist_user FOREIGN KEY (id) REFERENCES "users"(id) ON DELETE CASCADE
);

-- Fuzzy search index for psychologist names
CREATE INDEX IF NOT EXISTS trgm_idx_psychologists_name
    ON "psychologists"
    USING GIN (LOWER(name) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_psychologists_dni ON "psychologists" (dni);
CREATE INDEX IF NOT EXISTS idx_psychologists_specialty ON "psychologists" (specialty);

-- === Rooms Table ===
CREATE TABLE IF NOT EXISTS "rooms" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    capacity INTEGER DEFAULT 2,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rooms_active ON "rooms" (active) WHERE active = TRUE;

-- === Appointments Table ===
CREATE TABLE IF NOT EXISTS "appointments" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    patient_id BIGINT NOT NULL,
    psychologist_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    status VARCHAR(50) DEFAULT 'SCHEDULED',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES "patients"(id),
    CONSTRAINT fk_appointment_psychologist FOREIGN KEY (psychologist_id) REFERENCES "psychologists"(id),
    CONSTRAINT fk_appointment_room FOREIGN KEY (room_id) REFERENCES "rooms"(id),
    CONSTRAINT chk_time_order CHECK (end_time > start_time)
);

-- Performance indexes for conflict detection
CREATE INDEX IF NOT EXISTS idx_appointments_psychologist_time
    ON "appointments" (psychologist_id, start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_appointments_patient_time
    ON "appointments" (patient_id, start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_appointments_room_time
    ON "appointments" (room_id, start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_appointments_status ON "appointments" (status);

-- Exclusion constraints to prevent overlapping appointments (race condition safe)
ALTER TABLE "appointments" ADD CONSTRAINT no_psychologist_overlap
    EXCLUDE USING gist (
        psychologist_id WITH =,
        tsrange(start_time, end_time, '[)') WITH &&
    );

ALTER TABLE "appointments" ADD CONSTRAINT no_patient_overlap
    EXCLUDE USING gist (
        patient_id WITH =,
        tsrange(start_time, end_time, '[)') WITH &&
    );

ALTER TABLE "appointments" ADD CONSTRAINT no_room_overlap
    EXCLUDE USING gist (
        room_id WITH =,
        tsrange(start_time, end_time, '[)') WITH &&
    );

-- === Refresh Token Sessions Table ===
CREATE TABLE IF NOT EXISTS "refresh_token_sessions" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_id VARCHAR(255) UNIQUE NOT NULL,
    device_info VARCHAR(512),
    ip_address VARCHAR(45),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    replaced_by_token_id VARCHAR(255),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES "users"(id) ON DELETE CASCADE
);

-- Indexes for token lookups
CREATE INDEX IF NOT EXISTS idx_refresh_token_user_id
    ON "refresh_token_sessions" (user_id);

CREATE INDEX IF NOT EXISTS idx_refresh_token_token_id
    ON "refresh_token_sessions" (token_id);

-- Index for finding active sessions
CREATE INDEX IF NOT EXISTS idx_refresh_token_active
    ON "refresh_token_sessions" (user_id, revoked, expires_at)
    WHERE revoked = false;

-- Index for cleanup of expired tokens
CREATE INDEX IF NOT EXISTS idx_refresh_token_expires
    ON "refresh_token_sessions" (expires_at);

-- === Audit Log Table (for future use) ===
CREATE TABLE IF NOT EXISTS "audit_log" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100),
    entity_id BIGINT,
    old_value JSONB,
    new_value JSONB,
    ip_address VARCHAR(45),
    user_agent VARCHAR(512),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES "users"(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_user_id ON "audit_log" (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_action ON "audit_log" (action);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON "audit_log" (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_created_at ON "audit_log" (created_at);

-- === Helper Functions ===

-- Function to update updated_at timestamp automatically
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply trigger to all tables with updated_at column
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON "users"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_patients_updated_at
    BEFORE UPDATE ON "patients"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_psychologists_updated_at
    BEFORE UPDATE ON "psychologists"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_rooms_updated_at
    BEFORE UPDATE ON "rooms"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_appointments_updated_at
    BEFORE UPDATE ON "appointments"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- === Configuration ===
-- Set similarity threshold for fuzzy search
ALTER DATABASE mental_clinic SET pg_trgm.similarity_threshold = 0.1;

-- Log successful migration
DO $$
BEGIN
    RAISE NOTICE 'V1__initial_schema.sql: Schema created successfully';
    RAISE NOTICE 'Tables: users, patients, psychologists, rooms, appointments, refresh_token_sessions, audit_log';
    RAISE NOTICE 'Extensions: uuid-ossp, pg_trgm, btree_gist';
END $$;
